### ISSUE TITLE
Commitment Message vs EAP-TLS does not protect any application data

### ISSUE THREAD

**Issue by ms-s** [emu-wg/draft-ietf-emu-eap-tls13#13]
Section 2.4:
"While EAP-TLS does not protect any application data, the negotiated cipher suites and algorithms MAY be used to secure data as done in other TLS-based EAP methods."

Section 2.1.1:
"After the TLS handshake has completed and all Post-Handshake messages have been sent, the EAP server sends EAP-Success."
Even the figure that follows this statement shows that this is not true because there is still the Commitment Message.

**Comment by emanjon** [comment]
Fixed in recent commits
