### ISSUE TITLE
Consistent usage of terms EAP-TLS peer vs. EAP peer vs. EAP-TLS

### ISSUE THREAD

**Issue by ms-s** [emu-wg/draft-ietf-emu-eap-tls13#14]
The terms EAP-TLS peer, EAP-TLS, and EAP peer seem to be used interchangeably. It would be good to use the terms consistently.

 Here is an example from Section 5.8:
"EAP peers SHOULD use record padding, see Section 5.4 of [RFC8446] to reduce information leakage of certificate sizes."

In this example the reader is asked to understand that we are not talking about the EAP layer, nor about EAP-TLS with RFC 5216 but about the client and the server of EAP-TLS with TLS 1.3.

**Comment by emanjon** [comment]
Everything changes to EAP-TLS peer and EAP-TLS server.

Terminology explained in terminology section
