### ISSUE TITLE
Relation to RFC7525

### ISSUE THREAD

**Issue by ms-s** [emu-wg/draft-ietf-emu-eap-tls13#16]
Hannes says: If you want to reference RFC 7525 you should say what recommendation you want to carry over. If you don’t do that then the text should not be in contradiction of what is said in eap-tls13. 

RFC 7525 does not talk about EAP (and instead focuses on applications like  HTTP, SMTP, IMAP, POP, SIP, and XMPP, as noted in the abstract). RFC 7525, for example, does not mandate OCSP. It also recommends RSA, which draft-ietf-emu-eaptlscert and this draft does not do. There seems to be contradiction here.

At a minimum, I would clarify in the introduction what the updates to RFC 5216 are. This will help those implementers that focus on a variant of EAP-TLS that uses version 1.2.

**Comment by emanjon** [comment]
There are no contradictions with RFC7525 anymore. That RFC7525 does not mandate OCSP is not really a contradiction. Don't know if RSA was a contradiction, RFC7525 recommends support. Now when algorithms recommendations have been removed from EAP-TLS 1.3, RSA is at least not a problem. I still softened the requirement to follow RFC7525. RFC7525 have very many recommendations, it is also quite old and some od the recommendations might not be valid anymore.
