### ISSUE TITLE
Mandatory revocation checking when no CRL or OCSP available

### ISSUE THREAD

**Issue by ms-s** [emu-wg/draft-ietf-emu-eap-tls13#21]
Section 5.4

    When EAP-TLS is used with TLS 1.3, the revocation status of all the
    certificates in the certificate chains MUST be checked.

What does this mandatory checking entail when a certificate contains
neither a CRL Distribution Point nor an OCSP responder URL?  (See also
the recent thread on the LAMPS WG list with Subject: "The
id-ce-noRevAvail extension".)
Section 2.3

**Comment by emanjon** [comment]
That is a good point. In general I think we need to be a bit soft here and leave things to the application. All browsers use propriatary forms of CRL, some of them use OCSP, but e.g. Firefox "soft-fail" if the OCSP server is down.

The earlier agreement in EMU was that the group wanted MUST staple. Not sure that the group wants to allow very short lived certificates that cannot be revocation checked. Seems like a quite major change.

The agreement in LAMPS seem to be to not introduce a new extention and simply leave out CRL and OCSP from the cert.

**Comment by emanjon** [comment]
I would leave out short term certificates without any revocation checking possible unless it has been discussed in the group.

**Comment by ms-s** [comment]
I think maybe it is sufficient to just change MUST to SHOULD. If no CRL or OCSP is available, then deployments can ignore revocation checking without violating the specification.

**Comment by emanjon** [comment]
That would be a quite large change that would need to be discussed in the WG.

**Comment by emanjon** [comment]
Maybe the text could say that it is mandatory to check that the certificate has not been recently revocation and state that short lived certificates may fullfill this automatically.

Several persons in the WG wanted to make revocation checking more strict compared to RFC 5216. On the other hand we should not limit future deployments to much.

**Comment by ms-s** [comment]
I think we can close the this based on @2da98e0e8b1b5678aaa083ae27df0fae490650cc. Proprietary methods include no revocation checking or other ways of handling short live certificates.

**Comment by ms-s** [comment]
I think we can close the this based on 2da98e0e8b1b5678aaa083ae27df0fae490650cc. Propriatary methods include no revocation checking.
