### ISSUE TITLE
resumption without issuing new tickets

### ISSUE THREAD

**Issue by ms-s** [emu-wg/draft-ietf-emu-eap-tls13#24]
A subsequent authentication using resumption, where both sides
    authenticate successfully (without the issuance of more resumption
    tickets) is shown in Figure 3.

(It's slightly surprising to show an example of resumption without
issuing additional resumption tickets, since such issuance is basically
necessary in order to comply with the recommendation from earlier in the
section to follow the client tracking prevention mechanisms in Appendix
C.4 of RFC 8446.  Though I guess draft-ietf-tls-ticketrequests is
potentially relevant for just how necessary it is going to be in
practice.)

**Comment by emanjon** [comment]
Chaining tickets after each other gives quite bad security against key compromise. For IPsec, ANSSI recommends a new Diffie-Hellman key exchange every hour to improme security against key compromise.

The intention here was not that the client reuse the ticket. The intention was that the server requires a full handshake.

**Comment by emanjon** [comment]
I added a NewsessionTicket to the Figure.
