### ISSUE TITLE
alert plus fresh handshake

### ISSUE THREAD

**Issue by ms-s** [emu-wg/draft-ietf-emu-eap-tls13#25]
back to a full handshake.  If the EAP-TLS peer did not supply a
    "key_share" extension when attempting resumption, the EAP-TLS server
    needs to reject the ClientHello and the EAP-TLS peer needs to restart
    a full handshake.  The message flow in this case is given by Figure 4
    followed by Figure 1.

    Also during resumption, the EAP-TLS server can respond with a Hello
    Retry Request (see Section 2.1.6) or issue a new ticket (see
    Section 2.1.2)

I don't understand why the "alert plus fresh handshake" flow is even
listed as an option -- AFAICT the HelloRetryRequest (note: no spaces)
flow is uniformly superior.  There is no benefit in round-trip count to
starting a fresh handshake, and HelloRetryRequest allows the initial
interaction to be authenticated by the continued handshake transcript.
Aborting and starting over is analogous to the dreaded "downgrade dance"
that has periodically plagued the TLS ecosystem, and I'm confused that
we would consider encouraging it to return.  I would instead say that
the server "needs to send HelloRetryRequest to signal that additional
information is needed to complete the handshake, and the EAP-TLS peer
needs to send a second ClientHello containing that information" (or
similar), and drop the "Figure 4 followed by Figure 1" sentence.  (The
final paragraph would then become a bit redundant, but perhaps there is
still some information that should be persisted.)

**Comment by emanjon** [comment]
Good catch. I implemented the suggested text in 1490750 which should close this issue.
