### ISSUE TITLE
Should the draft say something about KeyUpdate

### ISSUE THREAD

**Issue by emanjon** [emu-wg/draft-ietf-emu-eap-tls13#27]
Both peers are allowed to send KeyUpdate according to TLS 1.3 (RFC 8446). Doing so directly after the handshake does not make that much sense, I think. Should the draft say something about the KeyUpdate message or even forbid its use?

**Comment by kaduk** [comment]
I don't think we should go as far as attempting to forbid it (which current implementations don't, IIRC, support), but noting that it's not useful and not expected could be reasonable.
