### ISSUE TITLE
Editorial for AUTH48: First generic paragraph in "mutual authentication" section

### ISSUE THREAD

**Issue by emanjon** [emu-wg/draft-ietf-emu-eap-tls13#29]
I noted that the first paragraph in section 2.1.1 is quite generic and not specific to "mutual authentication"

- One option is to move the paragraph out of the subsection, but the interactions with RFC5216 makes it tricky to move.
-  Another option is to rename "mutual authentication" back to "base case" which is what it is called in RFC5216.
 
This editorial change can wait until AUTH48.

**Comment by jsalowey** [comment]
Or perhaps just rename it to "Authentication"
