### ISSUE TITLE
Exporter use of context

### ISSUE THREAD

**Issue by emanjon** [emu-wg/draft-ietf-emu-eap-tls13#32]
Joe wrote that

"Personally, I think including the method byte in the context is a bit less
error prone and straight forward then including it in the label."

**Comment by emanjon** [comment]
I agree but I do not have strong opinions either. I do not see a theoretical problem with using the context. On the other hand, it is known that some implementations do not support use of context in the TLS exporter.

**Comment by jsalowey** [comment]
Are these implementations of TLS exporter or implementations of the RFC 5216 key derivation?  I think an RFC 5216 key derivation function will not work with TLS 13 in any case.

**Comment by emanjon** [comment]
They are implementations of the exporter. Mohit said that WolfSSL does not accept a context at all.
