### ISSUE TITLE
authenticated signal at the end of the handshake.

### ISSUE THREAD

**Issue by emanjon** [emu-wg/draft-ietf-emu-eap-tls13#33]
In the dicussion on the commitment message there has been quite a lot of talk about the need for an authenticated signal at the end of the handshake. This has not been discussed before.

- The -13 commitment message could not be used for that and close notify cannot be used for that.
- The NewSessionTicket could be used for this. This is a message that acknoledge that the server has accepted the client authentication. it is also a message that can only be sent be the server and not by an on-path attacker. Note that the NewSessionTicket is not cryptographically bound to the Clients second flight, but this is probably not needed.

Jorge Vergara wrote that an authenticated signal is probably not needed.

"1. I don't see a strict requirement for an authenticated signal at the end of the handshake."

This issue is likely related to the newly opened issue of the EAP state machine.

**Comment by jsalowey** [comment]
Most of the current discussion in the group is about result indications and not signaling the end of the handshake.  I doesn't seem that we need to signal the end of the handshake.  The peer should always know how long a flight of messages is even if they are fragmented.

**Comment by emanjon** [comment]
Agree, the protected result indications make any "end of handshake"-indication superfluous.

**Comment by jsalowey** [comment]
I think we can close this issue out once we have merged the application data as success indicator.

**Comment by jsalowey** [comment]
This will be resolved by merging PR #40, PR #55 and PR #46
