### ISSUE TITLE
attacks on availability

### ISSUE THREAD

**Issue by emanjon** [emu-wg/draft-ietf-emu-eap-tls13#36]
protected failure indicatioin gives the peer an authenticated way to know that the real server sent the failure. It does little or nothing to improve availability as basically any forged message makes TLS fall hard and fatal.

**Comment by jsalowey** [comment]
I don't think there is a way to protect the exchange from injection of errors without doing something more extreme like moving to DTLS.  It's also not clear that even if the method protected against it that many of the lower layers might have equivalent problems.

**Comment by emanjon** [comment]
"I don't think there is a way to protect the exchange from injection of errors" 
I don't think so either and think that is fine. I think the important availability goal is that the client and server can try again. I.e. an attacker needs to constantly be active to drop the handshake. 

I brought this up as Bernard stated that protected failure was important to improve availability. My conclusion is that protected failure does not improve availability as there are other easier was to drop the connection.

**Comment by jsalowey** [comment]
I agree with John's analysis. I think this can be closed.
