### ISSUE TITLE
SHOULD MUST Error

### ISSUE THREAD

**Issue by emanjon** [emu-wg/draft-ietf-emu-eap-tls13#38]
Alan suggests to make them MUST

RFC 8446 states optionally or SHOULD

**Comment by emanjon** [comment]
I implemented MUST Error in a pull request.

Alan "I would suggest instead that it MUST send the TLS alert before any EAP-Failure."
John: This would require also mandating user_cancelled.....

**Comment by emanjon** [comment]
To make a practical difference I think we need to follow Alans suggestion
and mandate a protected failure indication before EAP-Failure.

Looking at RFC 8446 it looks like TLS 1.3 can terminate a connection by:

- Not sending any alert
- Sending an Error alert
- Sending close_notify
- Sending user_cancelled
- Sending user_cancelled followed by close_notify
- (It would also not suprise me if some implementation
sends an Error alert followed by close_notify).

It seems a bit complicated to use alerts as both failure and success indications.

To make it work I think EAP-TLS 1.3 needs to:

- Forbid all use of user_cancelled
- Forbid close_notify except as success indication
- Mandate Error alert before EAP-Failure

Do implementors and TLS people agree that is possible?

Alternativeley

- Forbid close_notify except as success indication
- Mandate Error alert or user_cancelled before EAP-Failure

**Comment by kaduk** [comment]
I expect John already knows, but to link the github issues, there is some discussion at https://github.com/tlswg/tls13-spec/issues/1208 about "user_cancelled" and how some implementations don't really adhere to the text of 8446.

**Comment by jsalowey** [comment]
Any error alert set from the server should be treated as a failure signal regardless of what other information may be present.  I think a user_cancelled alert should be treated in the same way ( although I'm not sure there is reason for a server to send it so perhaps it should not be allowed).  

Any error alert or user cancelled from the peer should be treated as a failure indication from the peer and the server should respond with an EAP Failure.

Note: In [5216](https://www.rfc-editor.org/rfc/rfc5216.html#section-2.1.3) it is possible for the peer to send a client hello after receiving an alert from the server to restart the conversation.  I'm not sure that this changes anything.

**Comment by emanjon** [comment]
"Any error alert or user cancelled from the peer should be treated as a failure indication from the peer and the server should respond with an EAP Failure."

Yes, or "any alert should be treated as a failure indication" if we go with application data as a success indication.

"Note: In 5216 it is possible for the peer to send a client hello after receiving an alert from the server to restart the conversation. I'm not sure that this changes anything."

That's a good observation. Not sure we can allow that with TLS 1.3 if an alert is an failure indication.

BTW, my view is that draft-ietf-emu-eap-tls13 introduces protected result indicators when TLS 1.3 is used and does not update RFC 5216 with protected results when TLS 1.2 is used. I don't think this has not been clearly stated in the discussion. If somebody have a different view it would be good to know asap.

**Comment by jsalowey** [comment]
Correct, we should not change the behavior of 5216

**Comment by jsalowey** [comment]
This is resolved in PR #46
