### ISSUE TITLE
Guidance on Certificate identity checks

### ISSUE THREAD

**Issue by emanjon** [emu-wg/draft-ietf-emu-eap-tls13#47]
Joe started a mail thread based on the discussions around Ben's DISCUSS

https://mailarchive.ietf.org/arch/msg/emu/MuphKsTbv1Ty215sAIi-eRICHJc/

Topics mentioned:

- Include client certificates in key derivation
- Include identity response or other not TLS info in key derivation
- Guidance on how to chose certificate, and how to check identity in cert against expexted identity like is mandatory to do in HTTPS.

**Comment by emanjon** [comment]
In HTTPS, there is a tight connection between the host name the client tries to connect to and the host name in the subjectAltName of the servers certificate.

Reading RFC 5216 the the requirements seems to be quite fluffy. It seems fully possible to implement something conforming to RFC 5216 that lacks authentication.

- Peer sends identiry request @example.com
- On-path attacker change this to @example2.com and forwards it to example2.com realm
- Peer accepts server cert from example2.com

I don't want to suggest that EAP implementations are insecure. I assume this is taken care of by lower layers but I think it might be a problem that EAP-TLS does not mandate a secure behavior. I have recently seen people inplementing another security protocol using TLS without checking the received identity. This make everything completely authenticated as the client basically accepts any valid certificate signed by on the many trust achors the client is likely to have.

Would it make sense to mandate that the EAP-TLS peer MUST check the "realm" in the identity response with an identity in the EAP-TLS servers certificate?

**Comment by ms-s** [comment]
This was an issue in the past (mostly with eduroam and EAP-TTLS/EAP-PEAP). A server certificate from any trusted CA would be accepted by many peers and they would reveal the username/password inside. Now, the UI allows you to mention the server name so such attacks can be prevented. Some UIs however still make this optional. In windows 'Connect to these servers' is optional still?
https://www.esecurityplanet.com/wp-content/uploads/2020/11/tips-and-tricks-for-using-802-1x-in-windows_5facc11f361aa.png

**Comment by emanjon** [comment]
>Some UIs however still make this optional.

How do we formulate a short requirement that if followed ensures a secure implementation but without going into implementation details?

"The EAP-TLS peer MUST check that the identity in the EAP-TLS server's certificate agrees with the expected identity?"

or 

"The EAP-TLS peer MUST check that the identity in the EAP-TLS server's certificate agrees with the identity in the identity response?"

**Comment by ms-s** [comment]
The second sentence will not be completely correct in many deployments. I can give my personal example from Aalto. The identity response sent by a correctly configured peer is '@aalto.fi'. The server name check field in a correctly configured peer is 'radius.org.aalto.fi'.

**Comment by emanjon** [comment]
Further complication is that EAP allows the identity repsonse to contain any byte string, no format is mandatory.

What about:

"The EAP-TLS peer MUST check that the identity in the EAP-TLS server's certificate is appropriate and authorized for the link. If a NAI was used in the identity response, the EAP-TLS peer MUST check the realm in the identity response against the identity in the EAP-TLS server's certificate."

The second sentence would be very similar to what RFC 2818 (HTTPS) says about hostname.

**Comment by kaduk** [comment]
> In HTTPS, there is a tight connection between the host name the client tries to connect to and the host name in the subjectAltName of the servers certificate

FWIW, https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#https.verify has received some attention recently (most notably as a result of the http/3 work) but remains aligned with your description.

**Comment by emanjon** [comment]
Based on Alans comments I think the requirement should not be on identity. RFC 5216 might even go into to much details here while still missing the important security requirements.

- RFC 5216 requires that the client and server certificate is authorized for EAP-TLS but as far as I see is missing to require that the client and server certificate are associated with the specific link/network/access.

I think the requirement should be to authorize that the client and server certificate is authorized for EAP-TLS on the specific link/network/access. This does not even have to involve the identity.

- The client can be configured with a specific server certificate for the SSID and ignore the identity in the cert.
- The client can be configured with a specific trust anchor, or intermediate CA cert and all end-entity certs issued is authorized for EAP-TLS on for a specific SSID....

If the identity requirements in RFC 5216 are not followed in implementations they should be softened or removed.

**Comment by emanjon** [comment]
Alan has suggeted implementation guidance text describing how implementations currently work. This is rvery related but not the same as sequrity requirements.

**Comment by jsalowey** [comment]
The 5216 guidance here is lacking.  I'm thinking we should add some things to the security considerations for this, something like
1. Peers should allow for configuring a unique trust root and name to match against SANs of type DNS name. 
2. List the problems if your trust roots are overly broad and you do not have host name matching
3. Recommend that implementations provide ways to automate the provisioning of such names and trust roots.  
4. Perhaps say that implementation MAY implement a TOFU mechanism that allows a user to trust a particular certificate (I'm not sure how well this works in practice)

**Comment by ms-s** [comment]
I like the idea of 1-3. For 3, it might be worth mentioning how eduroam is doing it with the configuration assistant tool: https://www.eduroam.org/configuration-assistant-tool-cat/. Basically, you select your organization and it makes the necessary configurations on your OS. 

I am not sure I am comfortable with putting 4 in the document.

**Comment by jsalowey** [comment]
It does seem that 4 is common practice so it seems the document should say something about it.  For example: 
EAP-Peer implementations SHOULD prefer automated provisioning of information used to validate the server cert through a secure means instead of prompting the user to approve the server certificate on first use.  <go into some problems with accepting the certificate on first use such as MITM or breakage when certificate changes, expecting the user to make a decision they are not prepared to make.

**Comment by alandekok** [comment]
> The second sentence will not be completely correct in many deployments. I can give my personal example from Aalto. The identity response sent by a correctly configured peer is '@Aalto.fi'. The server name check field in a correctly configured peer is 'radius.org.aalto.fi'.

There are multiple issues here.

First is that the server name is a fully qualified DNS name.  The naiRealm is a subset of that, but there is no clear guidance on how to compare them.  You would hope that you could just check that the naiRealm is an exact suffix of the DNS name.  But that check is implicit, not explicit.  So any guidance here is only a suggestion, and isn't a definitive "we know that this works". 

Second, there's no requirement in TLS that the server name match the naiRealm used by the EAP peer.  We're adding that for EAP.  While is generally a good idea to recommend, we can't make it a MUST.

For example, a company may have multiple domains.  Such as when a company has multiple subsidiaries or has purchased other companies.  The certificate for users using naiRalm `@example.ca` could very well be `radius.example.com`.  So adding a hostname, and changing the last domain label.

Even RFC 7542 offers no guidance on comparing Realms to FQDNs.  It only defines that you can compare Realms, and that comparison is done on a byte-by-byte basis.

**Comment by jsalowey** [comment]
Since the key derivation issues are resolved I retitled this issue to be about certificate identity checks.

**Comment by ms-s** [comment]
@jsalowey and @alandekok here is a first rough draft of the text we could add to section 2.2 on Identity Verification. Feel free to bash this and improve:

   The EAP server identity in the TLS server certificate is typically a
   fully qualified domain name (FQDN).  EAP peer implementations SHOULD
   allow users to configuring a unique trust root (CA certificate) and a
   server name to authenticate the server certificate and match the
   subjectAlternativeName (SAN) extension in the server certificate with
   the configured server name.  In the absence of a user-configured root
   CA certificate, implementations MAY rely on system-wide root CA
   certificate bundles for authenticating the server certificate.  The
   process of configuring a root CA certificate and a server name is
   non-trivial and therefore automated methods of provisioning are
   RECOMMENDED.  For example, the eduroam federation [RFC7593] provides
   a Configuration Assistant Tool (CAT) to automate the configuration
   process.  In the absence of a trusted root CA certificate (user
   configured or system-wide), EAP peers MAY implement a trust on first
   use (TOFU) mechanism where the peer trusts and stores the server
   certificate during the first connection attempt.  The EAP peer
   ensures that the server presents the same stored certificate on
   subsequent interactions.

**Comment by alandekok** [comment]
That's a good step ahead.

**Comment by jsalowey** [comment]
@ms-s and @alandekok I'd like to include some text that indicates the problems with just relying on a preconfigured CA bundle and warn on TOFU.  Here is an edit :

The EAP server identity in the TLS server certificate is typically a
fully qualified domain name (FQDN). EAP peer implementations SHOULD
allow for the configuration of a unique trust root (CA certificate) and a
server name to authenticate the server certificate and match the
subjectAlternativeName (SAN) extension in the server certificate with
the configured server name. In the absence of a pre-configured root
CA certificate, implementations MAY rely on system-wide root CA
certificate bundles for authenticating the server certificate.  If server name matching is not used, then peers may end up trusting servers for EAP authentication that are not intended to be EAP servers.  If name matching is not used with a public CA bundle, then effectively any server can obtain a certificate that is trusted for EAP authentication by the Peer. 

The process of configuring a root CA certificate and a server name is
non-trivial and therefore automated methods of provisioning are
RECOMMENDED. For example, the eduroam federation [RFC7593] provides
a Configuration Assistant Tool (CAT) to automate the configuration
process.  In the absence of a trusted root CA certificate (explicitly
configured or system-wide), EAP peers MAY implement a trust on first
use (TOFU) mechanism where the peer trusts and stores the server
certificate during the first connection attempt.  Although, the EAP peer
can ensure that the server presents the same stored certificate on
subsequent interactions,  the TOFU mechanism does not allow for the certificate to be changed without out-of-band validation of the certificate and is therefore not suitable for many deployments.

**Comment by ms-s** [comment]
Based on d0c3d6f, closing this issue for now.
