### ISSUE TITLE
Key Derivation 

### ISSUE THREAD

**Issue by jsalowey** [emu-wg/draft-ietf-emu-eap-tls13#56]
I think we still need to come to consensus on where the EAP-Type goes

1. Label
2. Context

If the consensus is label then we need to determine how to incorporate IANA considerations as either a fixed string or reserve a prefix string

**Comment by ms-s** [comment]
I thought we had consensus during IETF 110 to use type-code in the context. I had closed #32 and merged PR #53

**Comment by jsalowey** [comment]
OK good, I hadn't seen the issue close and didn't realize there was a PR associated with it.  Closing this as resolved by PR #53
