### ISSUE TITLE
Handling Key Update

### ISSUE THREAD

**Issue by jsalowey** [emu-wg/draft-ietf-emu-eap-tls13#59]
From Alan's review

> Section 2.1.1 says:
> 
>    TLS 1.3 introduced the Post-Handshake KeyUpdate
>    message which is not useful and not expected in EAP-TLS. 
> 
> Q: What does it mean that the message is "not expected"?  This seems
> like a source of implementation-defined behavior, which experience
> shows has been a source of interoperability and security issues.
>

**Comment by kaduk** [comment]
I assume that "is not expected" means that EAP-TLS implementations have no reason to generate it ... since the connection is shut down immediately after the handshake completes, while the application_data traffic keys have hardly been used at all.  There's no reason to need to update the keys.

Whether or not we can usefully forbid the generation of KeyUpdate is perhaps another matter, though, and depends on what APIs are made available by TLS implementations.

**Comment by jsalowey** [comment]
It probably should say "implementations SHOULD NOT send a KeyUpdate message".  Can the implementation ignore a key update message if it receives it? Maybe "If a KeyUpdate message is received then an implementation SHOULD ignore the message and it SHOULD NOT sent a KeyUpdate message in response."

**Comment by jsalowey** [comment]
PR Merged

**Comment by jsalowey** [comment]
Re-opened issue based on Ben's PR comment

**Comment by ms-s** [comment]
I agree with what Ben wrote on the pull request trying to address this issue: "This doesn't actually match up; you have to process KeyUpdate if you're going to process any application data that comes after it. So either there is no application data and it's safe to ignore, or there might be application data and you have to process it"

**Comment by jsalowey** [comment]
@ms-s and @kaduk I think I agree with your point, can you suggest some better wording?  
I am also slightly worried that there is the possibility of ending up in a situation where you need to send a keyUpdate in response to a received keyUpdate that add extra round trips and increases the confusion on when the exchange is done.   Perhaps this isn't a real worry and it is sufficient to say "A peer SHOULD not send any additional TLS messages after it receives the success or failure result indication."  (we might have to account for the peer sending and error?)

**Comment by emanjon** [comment]
I don't see that anything more needs to be done here.

- "A peer SHOULD not send any additional TLS messages after it receives the success or failure result indication."
  I think this already follows from the current document.

KeyUpdate is not bound to application data. KeyUpdate should not be sent in EAP-TLS but if it is, it cannot be ignored. A NewSessionTicket or Error might also follow. We might not be able to control the TLS library on this. If keyupdate is sent I don't see that KeyUpdate ever causes any problem or increased roundtrips.

**Comment by jsalowey** [comment]
RFC 8446 says: 
"   If the request_update field is set to "update_requested", then the
   receiver MUST send a KeyUpdate of its own with request_update set to
   "update_not_requested" prior to sending its next Application Data
   record."

If no application data is going to be sent then presumably a keyUpdate does not need to be sent so I think you are right that it should not increase round trips.  If the TLS layer receives update  with update_requested and it has more TLS messages to send it can add the KeyUpdate.  If it does not include the key update is shouldn't really be a problem either.  

I think we can close this issue.
