### ISSUE TITLE
Draft 15 uses draft-ietf-tls-rfc8446bis terminology

### ISSUE THREAD

**Issue by h-vn** [emu-wg/draft-ietf-emu-eap-tls13#73]
While reading draft-ietf-emu-eap-tls13-15 I noticed that section [2.3. Key Hierarchy](https://datatracker.ietf.org/doc/html/draft-ietf-emu-eap-tls13-15#section-2.3) now uses `exporter_secret` which is the named used in [RFC 8446 update draft](https://datatracker.ietf.org/doc/html/draft-ietf-tls-rfc8446bis-01#section-7.1) but not in RFC 8446 itself. I first thought this was a typo, before a further look showed that this change was mentioned in IETF 110 [meeting slides](https://datatracker.ietf.org/meeting/110/materials/slides-110-emu-eap-tls-with-tls-13-00).

Suggestion: make clear which parts need to be looked up from RFC 8446bis. In addition to exporter terminology, the meeting slides above also discuss about _user_cancelled behavior_ on slide 10. For clarity, any updates from RFC 8446bis should be marked clearly.

**Comment by jsalowey** [comment]
It would be best not to have normative references that block on RFC 8446bis.  Perhaps we can just reference that it is renamed from "exporter_master_secret"

**Comment by h-vn** [comment]
> It would be best not to have normative references that block on RFC 8446bis. Perhaps we can just reference that it is renamed from "exporter_master_secret"

Sounds good. That should make clear where it comes from and that there's no need to file errata about unknown term and/or RFC 8446bis dependency. 

Taking another look at my comment about _user_cancelled behavior_ on slide 10; to clarify what I was meaning: The slides hint that clarifications in 8446bis are needed by EAP-TLS too. If so, this looks like a reference to RFC 8446bis too.

Finally, one nit: the alert name in RFC 8446 is "user_cance**l**ed", not "user_cance**ll**ed" as in draft -15.

**Comment by emanjon** [comment]
I made a PR with explaining that the document use the terminology from RFC8446bis.

https://github.com/emu-wg/draft-ietf-emu-eap-tls13/pull/75

Do we need to say anything about user_cancelled? RFC8446bis might do several clarifications and corrections. I think we should only mention things that are directly relevant for EAP-TLS 1.3

https://github.com/tlswg/tls13-spec/issues/1208

Current plan for RFC8446bis seems to be to ignore close_notify and I assume require close_notify after. This does not seem directly relevant for EAP-TLS 1.3. Or?

**Comment by emanjon** [comment]
close issue?

**Comment by h-vn** [comment]
Yes, please close this. I think it's now clear where exporter_secret comes from.

Also, thanks for the pointer to TLSv1.3 discussion.  I agree user_canceled followed by close_notify discussion is not relevant for EAP-TLS 1.3. It's seems to be TLSv1.3 specification and implementation level detail as opposed to something that EAP-TLS 1.3 needs to directly react on.
