### ISSUE TITLE
Review by John

### ISSUE THREAD

**Issue by emanjon** [emu-wg/draft-ietf-emu-eap-tls13#76]
- "TLS 1.3 significantly improves privacy when compared to earlier versions of TLS by forbidding cipher suites without confidentiality"

This is not true as TLS 1.3 now has has cipher suites without confidentiality. Needs to be reformulated in terms of EAP-TLS 1.3 which states that confidentiality is mandated in another part of the document.

-"EAP-TLS with TLS 1.3 exports the MSK and does not specify how it used by lower layers."

NIT should be "it is used"

- "EAP peers MAY implement a trust on first use (TOFU) mechanism where the peer trusts and stores the server certificate during the first connection attempt. The EAP peer ensures that the server presents the same stored certificate on subsequent interactions.  Use of TOFU mechanism does not allow for the server certificate to change without out-of-band validation of the certificate and is therefore not suitable for many deployments."

This needs security considerations.

**Comment by jsalowey** [comment]
TLS 1.3 never forbade anything with respect to cipher suites.  It just didn't define any.   But I agree that the document should require cipher suites that provide confidentiality.  

Any suggestions for security considerations?  

How about "TOFU mechanisms increase the susceptibility to traffic interception attacks and should only be used if there are adequate controls in place to mitigate this risk. "?

**Comment by emanjon** [comment]
Fixed in -17
