### ISSUE TITLE
Clarify Applicability to Earlier versions of TLS

### ISSUE THREAD

**Issue by jsalowey** [emu-wg/draft-ietf-emu-eap-tls13#79]
Most of the document applies only when TLS 1.3 is negotiated.  The document should make clear that this is the case and explicitly point out areas that are applicable to earlier versions (if any) 
This issue was raised on the list be Bernard Aboba and relates to issues raised by Alan Dekok as well.

**Comment by jsalowey** [comment]
Should any of this document apply to earlier versions of EAP-TLS or should it just apply to EAP-TLS when TLS 1.3 is negotiated.

**Comment by emanjon** [comment]
>Should any of this document apply to earlier versions of EAP-TLS or should it just apply to EAP-TLS when TLS 1.3 is >negotiated.

That was the intention from the beginning, but this is not true anymore because of Section 5.7 "Resumption". 
  
   "This is a new section when compared to [RFC5216].  The guidance in
   this section is relevant for EAP-TLS in general (regardless of the
   underlying TLS version used)."

**Comment by emanjon** [comment]
Agree with Bernard regarding that

"> The only way this makes sense to me is if it is stated that
> draft-ietf-emu-eap-tls13 applies only when TLS 1.3 is negotiated, and that
> if TLS 1.2, 1.1 or 1.0 is negotiated, then RFC 5216 applies."

should be explicitly stated. Howerer TLS 1.1 and TLS 1.0 should not be explicitly talked about as IETF has formally forbidden support. I'll add something like

"Except for Section 5.7, this document applies only when TLS 1.3 is negotiated. When TLS 1.2 is negotiated, then RFC 5216 applies."

**Comment by emanjon** [comment]
As pointed out by Joe the draft should maybe also state "The EAP-TLS
implementation does need to know which version of TLS is negotiated."

**Comment by emanjon** [comment]
This needed some additional changes as Section 2.2 according to #82 applies to TLS 1.2

**Comment by emanjon** [comment]
Fixed in -17
