### ISSUE TITLE
New Handshake messages

### ISSUE THREAD

**Issue by jsalowey** [emu-wg/draft-ietf-emu-eap-tls13#80]
TLS introduces some new handshake messages.   In general, these will just be handled by the underlying TLS library.  

"TLS 1.3 introduces several new handshake messages including HelloRetryRequest, NewSessionTicket, KeyUpdate.  In general, these messages will be handled by the underlying TLS libraries and are not visible to EAP-TLS, however there are a few things to note.  

The HelloRetryRequest is used by the server to reject the parameters offered in the ClientHello and suggest new parameters.  When this message is encountered it will increase the number of round trips used by the protocol.  

The NewSessionTicket message is used to convey session resumption information and is covered in sections 2.1.2 and 2.1.3.  

The KeyUpdate message is used to update the encryption keys used on a TLS connection.  EAP-TLS does not encrypt significant amounts of this data so this functionality is not needed.  Implementations SHOULD NOT send this message, however some TLS libraries may automatically generate and process this message.   (remove current text on KeyUpdate)

Early Data MUST NOT be used in EAP-TLS.   EAP-TLS servers MUST NOT send and early_data extension and clients MUST NOT send an EndOfEarlyData message.

Servers MUST NOT use post handshake authentication."

**Comment by emanjon** [comment]
I made some minor rewording, plese check PR #83

**Comment by jsalowey** [comment]
This is addressed by PR #83

**Comment by emanjon** [comment]
Fixed in -17
