### ISSUE TITLE
Indicate new specification behavior

### ISSUE THREAD

**Issue by jsalowey** [emu-wg/draft-ietf-emu-eap-tls13#82]
Section 2.2 specifies some behavior that is widely implemented, but not covered in RFC 5216.  This should be indicated:

"While this requirement to verify domain names is new, and was not mentioned in [RFC5216], it has been widely implemented in EAP peers.  As such, we believe that this section contains minimal new interoperability or implementation requirements on EAP peers and can be applied to earlier versions of TLS.

**Comment by emanjon** [comment]
Fixed in -17
