### ISSUE TITLE
Use of certificates in multiple protocols

### ISSUE THREAD

**Issue by alandekok** [emu-wg/draft-ietf-emu-eap-tls13#86]
There appears to be no text discussing the issue of certificate use across multiple protocols.  I would suggest adding the following:

5.11 Certificate Reuse

Certificates used for EAP-TLS MUST NOT be used in any other protocol besides EAP.  Section 2.2 above suggests that certificates typically have one or more FQDNs in the SAN extension.  However, those fields are for EAP validation only, and do not indicate that the certificates are suitable for use on WWW (or other) protocol server on the named host.

Allowing the same certificate to be used in multiple protocols would possibly allow for an attacker to authenticate via one protocol, and then "resume" that session in another protocol.   Section 5.7 above suggests that authorization rules should be re-applied on resumption, but does not mandate this behavior.  As a result, this cross-protocol resumption could allow the attacker to bypass authorization policies, and  toobtain undesired access to secured systems.  The simplest way to prevent this attack is to forbid the use of the same certificate across multiple protocols.

**Comment by jsalowey** [comment]
Maybe the title should be cross protocol attacks.  It's not clear to me that using different certs will always help.  If the resumption cache is shared between implementations then even if the server uses a different cert its possible that it ignores the difference on resumption.  Perhaps we should consider defining an ALPN EAP-TLS.  

5.11 Cross-Protocol attacks

Allowing the same certificate to be used in multiple protocols would possibly allow for an attacker to authenticate via one protocol, and then "resume" that session in another protocol. Section 2.2 above suggests that certificates typically have one or more FQDNs in the SAN extension. However, those fields are for EAP validation only, and do not indicate that the certificates are suitable for use on WWW (or other) protocol server on the named host.

Section 5.7 above suggests that authorization rules should be re-applied on resumption, but does not mandate this behavior. As a result, this cross-protocol resumption could allow the attacker to bypass authorization policies, and to obtain undesired access to secured systems.  Along with making sure that appropriate authorization information is available and used during resumption, using different certificates and resumption caches for different protocols is RECOMMENDED to help keep different protocol usages separate.

**Comment by alandekok** [comment]
On Jun 23, 2021, at 4:27 PM, jsalowey ***@***.***> wrote:
> Maybe the title should be cross protocol attacks. It's not clear to me that using different certs will always help. If the resumption cache is shared between implementations then even if the server uses a different cert its possible that it ignores the difference on resumption.

  That's true, and a possibility I hadn't considered.

>  Perhaps we should consider defining an ALPN EAP-TLS.

  That might be useful.  Given the time frame for this document, I think we might just leave it for an extension / update.

> 5.11 Cross-Protocol attacks
> 
> Allowing the same certificate to be used in multiple protocols would possibly allow for an attacker to authenticate via one protocol, and then "resume" that session in another protocol. Section 2.2 above suggests that certificates typically have one or more FQDNs in the SAN extension. However, those fields are for EAP validation only, and do not indicate that the certificates are suitable for use on WWW (or other) protocol server on the named host.
> 
> Section 5.7 above suggests that authorization rules should be re-applied on resumption, but does not mandate this behavior. As a result, this cross-protocol resumption could allow the attacker to bypass authorization policies, and to obtain undesired access to secured systems. Along with making sure that appropriate authorization information is available and used during resumption, using different certificates and resumption caches for different protocols is RECOMMENDED to help keep different protocol usages separate.

  That's good.

  TBH, we really should use a "key purpose" specifically for EAP, instead of re-using id-kp-serverAuth.  But that ship has sailed.

**Comment by emanjon** [comment]
Given https://mailarchive.ietf.org/arch/msg/emu/PBO_K3x_66exDur7GUYn5G41Ssw/ this seems to be still in discussion. I will submit version -17 now based on guidance from the Shepard and leave this open. I have closed all other issues.

I am personally fine with the text suggested by Joe. I don't know how common it would be to share resumption caches between a EAP server and a HTTP server.

Could an EAP server implementation want to use the EAP-TLS cert from HTTPS on a management interface?

My feeling would be that is should be RECOMMENDED to not use the same cert, and MUST NOT allow resumption between protocols.

**Comment by alandekok** [comment]
On Jun 26, 2021, at 9:46 AM, John Mattsson ***@***.***> wrote:
> Given https://mailarchive.ietf.org/arch/msg/emu/PBO_K3x_66exDur7GUYn5G41Ssw/ this seems to be still in discussion. I will submit version -17 now based on guidance from the Shepard and leave this open. I have closed all other issues.
> 
> I am personally fine with the text suggested by Joe. I don't know how common it would be to share resumption caches between a EAP server and a HTTP server.

  It's rare, and likely exceedingly rare.  But possible.

  i.e. in my case, we put resumption caches into a DB, for high availability and scalability.  This allows a user to authentication to server A, and then do resumption on machine B.

  Once the resumption cache is in a DB, then anything can access it.

> Could an EAP server implementation want to use the EAP-TLS cert from HTTPS on a management interface?

  I could see vendors wanting to do that for simplicity, but I think it's a bad idea.

> My feeling would be that is should be RECOMMENDED to not use the same cert, and MUST NOT allow resumption between protocols.

  I agree.

**Comment by emanjon** [comment]
@jsalowey @alandekok @ms-s 

Seems to be quite much agreement here. We should add this to the -19 version that will then be sent on another IETF last call.

**Comment by ms-s** [comment]
Thank you @alandekok and @jsalowey for the text. Added in 55ccd04
